import os
import io
import numpy as np


# Function for turning pairs of letters into single letters 
def substitute(pairs):

	pairs = pairs.replace('AA', 'A')
	pairs = pairs.replace('AD', 'B')
	pairs = pairs.replace('AF', 'C')
	pairs = pairs.replace('AG', 'D')
	pairs = pairs.replace('AX', 'E')
	pairs = pairs.replace('DA', 'F')
	pairs = pairs.replace('DD', 'G')
	pairs = pairs.replace('DF', 'H')
	pairs = pairs.replace('DG', 'I')
	pairs = pairs.replace('DX', 'K')
	pairs = pairs.replace('FA', 'L')
	pairs = pairs.replace('FD', 'M')
	pairs = pairs.replace('FF', 'N')
	pairs = pairs.replace('FG', 'O')
	pairs = pairs.replace('FX', 'P')
	pairs = pairs.replace('GA', 'Q')
	pairs = pairs.replace('GD', 'R')
	pairs = pairs.replace('GF', 'S')
	pairs = pairs.replace('GG', 'T')
	pairs = pairs.replace('GX', 'U')
	pairs = pairs.replace('XA', 'V')
	pairs = pairs.replace('XD', 'W')
	pairs = pairs.replace('XF', 'X')
	pairs = pairs.replace('XG', 'Y')
	pairs = pairs.replace('XX', 'Z')
	pairs = pairs.replace(' ', '')

	return pairs;


"""
Main program
"""

ct = "XD DD AD DA GD AA DX FG DA XF AA AD DD GA AF GX GD XA GF DA XX AG GG GD AA DA GX XD GF AG AG AG AF GX AF DF XD FD AG AG FX GX AD GA XA GF DG AA GD FG GG GF AD FA FX XG GD AD AA GD AG FA DX XD FD GA GG GG FF DG AF XF XD DG AD FG GF DG DA GX DX DA XF XX GD AA FF FA GX GA AD FD GA AF DA DA DG GA FA AD DD AX DA FG FG AD FA DD DG GA GF FD GA AF DA XG FA XX FA GD GG GA GX GG FX AD XD DG AG FA GD AX AD AA DD FG DA AF FD DG GG AF GD XA DX GA DA AD GF GG DX GD GX FX XD GA GG DF GG AD XD DX GF DF FX AF GD AA GG FD DG XA DG DX GG AG GX DG AX GD FX AF DD GD AG GG XF GA XA AX GX GA FD DX FD XF GA FA XX FD GA DA GA AF XG GD AX AA GF GX GF DD FA GG DF XG XD DA AA AD GF AX AG FF FF GG GG DF DA FG GA XX DA AD GX DG AX AG GG FA AD FA XG XD FA XF AA GX FG DG AX AF AG AD FX GF DD AG AD FA FX DG FF XA DA AG GA XX DA AD XG GG DX FD GF FG AD AD AA AF GG DA DX AF AG DA GX AD DF DD FA AG AF FG AD DF XX XD DA AA AD GD GA GG AX AF GF AG DF GX FF AX FA DD DG XA FG XA DA XA GF GX DA XF GX GX DD DA FG DA FA FG AD GD DD AX GG DG GG AD DX XG AF FA AD AD DD FA AF GX GF AA AG AD GD DA AA XA AF DF XD FD AG AG FX GX AD GA FA GX GF DA AD GF AX AG FF DX XX FF GX DD GD DA AG XA AF DA GG DF DF DG FG DG AA GD XD AG FG GD FD DA FA FG AG GF DF AX AG GF DG AD AA AX DD GA AF GF AD GX DG GG GD AX DG XX FG DG FA DX FG XD XD FF GX XF DD DD DD FA AX DA FX XA DG DG GX DG XG DG XX DA AD DF AX DD AD DA FG XX GG AX FD AG DX GF DA FD XA GD XA AA FD FF AD GG GD DX AA FD DF AF DX AD XA AG AF FA GD GG FF AX AG DA FF FD FG XA GG AD FA GA AX XA XD DA FA GG DF DX DG GA GX DA GX AX DG AG AX DG AF FA AG FG AX FD DD GX DG GA XA AF GG AX AG DF DD XG FG AD AA GX AA DD DG FD FG DA XD AX GG XD GF GD GA DA FX GG GA AG XA FG FD GA AF AF DG DA AF AX GA FA DF XD AX DX AX AA FG AA DG GG AD AF DD DD DG XD DG FG GG AD FA FD DG GD FA GA AG AF XF GG DF DF DF AA FD DG XA XG DD GA AA GX DD GA FG GG DG AX AD AA GF XG DG FG DD DG AA AG DD DF XG DF AD GF AD AD XX XF GX AG DF FG FX AD AD AX GX FF XD GG GG DA XG FG AD DA FG XA FD XG DD AX DA DD GX AA FD FF XG FX GF DA GA AA AF DA AG DG AA FD DG XD XD XF DG AG GF GX FA FX XX XF GF XX AD FA DD DD DD AX AA DG XD GF FD FA XG GX XD FA AF DX FD AA DD AG XX AG AD FA XA AF GD FA XF GX DA GG GA DA XG GA DX GG XD AD AF DA FF GA DX FG XA AF XD AA FA FF AA GD FD DD DG XD DD DA DF GF DD GX DG AX GD FD DA AF AA AG GG XF AD AX FX GD DX FG AD FD DG FF XD FD GA XF AG AD AA DF AD FG XD FG XA AG DD XA AF DG GX XG FD GA FA GA FA DA GA XX AA XD AA GG GF GX DG GA DX DD AG AD GD FA DD GF XD AD DD FD XD DF XF XX AX DA GF DD AG XX XG GG GD FG GF DD GA GA XX GF GG AX XF DA FX XA GA DA DD GG FX XA AF DA GD FF XA AX GG AX GF DA FG XG XG FX FA FG AA AF AF DD XA AG XG FA GX DG XG FG AD FA DX AA DG AG GX GF DG DA XX FA GD GF GA GD DD FD FG DD AG FX FF AF DD XG DA AX AA FA GX GF GG FG AD FA GA DF AG XG AD GG AD AA DA XX AA AG DG AD GF GA XG GD XA GX DD AA FF FF DG XG DA AF AD GF XG AX GD DA AG AX AA DG FD XG GA DG GG GX DX DD XG GG GX XA AG GG AF AF FD AD DF XX FF DD DX DA DD DX GD DG DD GD XF FX AG GX GF AA AG DG DA DD GA DA AF XD DG FG DX FD GD GD XF DG GA DX GX GG GF AD XA GG DA GG DX AX XD FD GD GD DF FX AD AX AG DA FG FF FA XF XA XA AD AA XD DX FF AX XG FG DD FA GD GA DG FA DD AG FA GA DF AD DX DD DG DD DG DF XG DA DD DD DF AA AD GG AA DA AD AD DX GG FF AD XF GG AA GG GA DX GF XF GA AD GA XX XG GX XG DX FA FD FA DF XG AG FG FX FD GF FX AG FA XA AX FF XA AA XD XD DX FG GD AX FF XA GF FD GA FG AX XG GD AX DD AD FA GD XD GG DD FG AG FX FD AG FG DG AD AA XG FD GA XX GF GX DD DD GD AD AG FF GG DF FA DA GA AA DX DX AD FD XD DD AA AD FD AA GF XG DF DA GD AG FA DG DA FG DG DA FG FF DG GA AF DG FG XX FA XF GD DG GG XD GX DF AD FG FA GF XG GD FG XA FG XD GA GG FA AF DG DD DG GG GX FD GA GF AD DX DA AF FG AD GG GF FX DG GA XX AD GD FD AF GG XA XG DA FX XF XX FF XX GX XF FX XF FF"
print(substitute(ct))
